# Generated by Django 5.1.2 on 2024-10-30 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='inntro',
            new_name='intro',
        ),
    ]
