# Generated by Django 5.1.2 on 2024-11-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0002_rename_inntro_article_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='banner',
            field=models.ImageField(blank=True, default='image.png', upload_to=''),
        ),
    ]
