# Generated by Django 5.1.2 on 2024-11-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0003_article_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
